### ISSUE TITLE
getTransactionsToApprove documentation

### ISSUE THREAD

**Issue by alongalky** [iotaledger/docs#2]
The Input and Output sections are [both not relevant](https://docs.iota.org/iri/api#endpoints/getTransactionsToApprove). It should be copied from [here](https://iota.readme.io/reference#gettransactionstoapprove). In addition, there is an important missing parameter called `reference` which should be added to the input section.

**Comment by l3wi** [comment]
This has been removed from scope of the docs. Please update on iota.readme.io
